### ISSUE TITLE
想请教一些问题

### ISSUE THREAD

**Issue by YaoJuan** [SPStore/HVScrollView#4]
目前自己仿写一个类似微博的效果，但是要更适合自己项目，所以做了一些细节的变化。例如下方scrollview用collectonView代替了。但是自己遇到了一些问题，例如第一个,当在下方子tableview斜方向滑动时，下方会同时切换并且往上走。类似右上左上这种移动。第二个在监听所有子table的通知方法中，老是会因为外层tableview的bounces的原因使得外层table的offset.y小于了header 从而提前让子table回到归零位了。请您指教一下

**Comment by BichKhun** [comment]
我也是这样，子tableview滑不上去，不知道你最后解决了吗
